### ISSUE TITLE
Ideas for RAP group

### ISSUE THREAD

**Issue by jvcasillas** [RAP-group/meetings#1]
- lab tiktok/instagram/youtube
- website
  - [x] fotos
  - [x] ideas for blog posts

**Comment by jvcasillas** [comment]
Blog post ideas

- short sci-com write-up of DPBE study
- short sci-com write-up of empathy study
- Celebratory post for Nicole's post-doc 
- Celebratory post for Juanjo's job

**Comment by jvcasillas** [comment]
@GaboSJW @GabrielaConstantin-Dureci In yesterday's meeting we discussed sending a proposal to the special issue in SSLA on replications. The info is here: https://github.com/RAP-group/meetings 
For next week we are all going to come with a few candidates for a replication study.

**Comment by jvcasillas** [comment]
Possible co-authors for multi-site replication: 

- [x] Juanjo (Furman)
- [ ] Miquel Simonet (UA)
- [ ] Rajiv Rao (UW)
- [ ] Danielle Daidone (UNCW)
- [ ] Gillian Lord (UF)
- [x] Mark Amengual (UCSC)
- [ ] Brandon Baird (Middlebury)
- [ ] Matt Carlson (Penn State)
- [ ] Rebeka Campos-Astorkiza (OSU)
- [ ] José Ignacio Hualde (UIUC)

**Comment by jvcasillas** [comment]
1. [Effects of bilingualism, noise, and reverberation on speech perception by listeners with normal hearing](https://www.cambridge.org/core/journals/applied-psycholinguistics/article/effects-of-bilingualism-noise-and-reverberation-on-speech-perception-by-listeners-with-normal-hearing/884F052D4A8D4672ACB3F492107DA2B1)
2. [The acquisition of /r/ and /l/ by Japanese learners of English: Evidence that speech production can precede speech perception](https://www.cambridge.org/core/journals/applied-psycholinguistics/article/abs/acquisition-of-r-and-l-by-japanese-learners-of-english-evidence-that-speech-production-can-precede-speech-perception/2AA96D62D2FCE297EA9F5E7A24D6B111)
3. [Interlingual influence in bilingual speech: Cognate status effect in a continuum of bilingualism](https://www.cambridge.org/core/journals/bilingualism-language-and-cognition/article/interlingual-influence-in-bilingual-speech-cognate-status-effect-in-a-continuum-of-bilingualism/77D8670E8A6008B1349AC4EA011537BE)
4. [A critical period for second language acquisition: Evidence from 2/3 million English speakers](https://www.sciencedirect.com/science/article/pii/S0010027718300994?via%3Dihub)
5. [The Effects of Nonnative Accents on Listening Comprehension: Implications for ESL Assessment](https://www.jstor.org/stable/3588329?seq=1#metadata_info_tab_contents)
6. [Keeping a Critical Eye on Majority Language Influence: The Case of Uptalk in Heritage Spanish](https://www.mdpi.com/2226-471X/6/1/13)
7. [Rhythmic Abilities Correlate with L2 Prosody Imitation Abilities in Typologically Different Languages](https://journals.sagepub.com/doi/10.1177/0023830919826334)

Did I miss one?




Other ideas (not a replication)

- MAPPING SECOND LANGUAGE LEARNERS’ ACCENT OF SPANISH
	- https://www.internationalphoneticassociation.org/icphs-proceedings/ICPhS2015/Papers/ICPHS0677.pdf

**Comment by IvanAndreuRascon** [comment]
Este es mi orden de preferencia


1. [Effects of bilingualism, noise, and reverberation on speech perception by listeners with normal hearing](https://www.cambridge.org/core/journals/applied-psycholinguistics/article/effects-of-bilingualism-noise-and-reverberation-on-speech-perception-by-listeners-with-normal-hearing/884F052D4A8D4672ACB3F492107DA2B1)

 2. [The acquisition of /r/ and /l/ by Japanese learners of English: Evidence that speech production can precede speech perception](https://www.cambridge.org/core/journals/applied-psycholinguistics/article/abs/acquisition-of-r-and-l-by-japanese-learners-of-english-evidence-that-speech-production-can-precede-speech-perception/2AA96D62D2FCE297EA9F5E7A24D6B111)

 3. [Rhythmic Abilities Correlate with L2 Prosody Imitation Abilities in Typologically Different Languages](https://journals.sagepub.com/doi/10.1177/0023830919826334)

 4. [Interlingual influence in bilingual speech: Cognate status effect in a continuum of bilingualism](https://www.cambridge.org/core/journals/bilingualism-language-and-cognition/article/interlingual-influence-in-bilingual-speech-cognate-status-effect-in-a-continuum-of-bilingualism/77D8670E8A6008B1349AC4EA011537BE)

5. [The Effects of Nonnative Accents on Listening Comprehension: Implications for ESL Assessment](https://www.jstor.org/stable/3588329?seq=1#metadata_info_tab_contents)

6. [Keeping a Critical Eye on Majority Language Influence: The Case of Uptalk in Heritage Spanish](https://www.mdpi.com/2226-471X/6/1/13)


7. [A critical period for second language acquisition: Evidence from 2/3 million English speakers](https://www.sciencedirect.com/science/article/pii/S0010027718300994?via%3Dihub)

**Comment by GabrielaConstantin-Dureci** [comment]
1.  The Effects of Nonnative Accents on Listening Comprehension: Implications for ESL Assessment
2.  The acquisition of /r/ and /l/ by Japanese learners of English: Evidence that speech production can precede speech perception
3. Effects of bilingualism, noise, and reverberation on speech perception by listeners with normal hearing
4. Keeping a Critical Eye on Majority Language Influence: The Case of Uptalk in Heritage Spanish
5. Interlingual influence in bilingual speech: Cognate status effect in a continuum of bilingualism
6. Rhythmic Abilities Correlate with L2 Prosody Imitation Abilities in Typologically Different Languages
7. A critical period for second language acquisition: Evidence from 2/3 million English speakers

**Comment by kparrish92** [comment]
1. Effects of bilingualism, noise, and reverberation on speech perception by listeners with normal hearing
2. Rhythmic Abilities Correlate with L2 Prosody Imitation Abilities in Typologically Different Languages
3. The Effects of Nonnative Accents on Listening Comprehension: Implications for ESL Assessment
4. Interlingual influence in bilingual speech: Cognate status effect in a continuum of bilingualism
5. The acquisition of /r/ and /l/ by Japanese learners of English: Evidence that speech production can precede speech perception
6. Keeping a Critical Eye on Majority Language Influence: The Case of Uptalk in Heritage Spanish
7. A critical period for second language acquisition: Evidence from 2/3 million English speakers

**Comment by juanjgarridop** [comment]
1. Rhythmic Abilities Correlate with L2 Prosody Imitation Abilities in Typologically Different Languages 
2. Effects of bilingualism, noise, and reverberation on speech perception by listeners with normal hearing
3. Interlingual influence in bilingual speech: Cognate status effect in a continuum of bilingualism
4. The acquisition of /r/ and /l/ by Japanese learners of English: Evidence that speech production can precede speech perception
5. Keeping a Critical Eye on Majority Language Influence: The Case of Uptalk in Heritage Spanish
6. The Effects of Nonnative Accents on Listening Comprehension: Implications for ESL Assessment
7. A critical period for second language acquisition: Evidence from 2/3 million English speakers

**Comment by laurafdeza** [comment]
1. Effects of bilingualism, noise, and reverberation on speech perception by listeners with normal hearing
2. Rhythmic Abilities Correlate with L2 Prosody Imitation Abilities in Typologically Different Languages
3. Keeping a Critical Eye on Majority Language Influence: The Case of Uptalk in Heritage Spanish
4. The acquisition of /r/ and /l/ by Japanese learners of English: Evidence that speech production can precede speech perception
5. The Effects of Nonnative Accents on Listening Comprehension: Implications for ESL Assessment
6. Interlingual influence in bilingual speech: Cognate status effect in a continuum of bilingualism
7. A critical period for second language acquisition: Evidence from 2/3 million English speakers

**Comment by GaboSJW** [comment]
1. Keeping a Critical Eye on Majority Language Influence: The Case of Uptalk in Heritage Spanish
2. Rhythmic Abilities Correlate with L2 Prosody Imitation Abilities in Typologically Different Languages
3. Effects of bilingualism, noise, and reverberation on speech perception by listeners with normal hearing
4. Interlingual influence in bilingual speech: Cognate status effect in a continuum of bilingualism
5. The Effects of Nonnative Accents on Listening Comprehension: Implications for ESL Assessment
6. The acquisition of /r/ and /l/ by Japanese learners of English: Evidence that speech production can precede speech perception
7. A critical period for second language acquisition: Evidence from 2/3 million English speakers
