### ISSUE TITLE
Project teams

### ISSUE THREAD

**Issue by jvcasillas** [RAP-group/meetings#2]
Say what project you want to work on. 

1. open science for grad students and advisors
2. data sharing in linguistics 
3. claros website

**Comment by kparrish92** [comment]
I am interested in contributing to all of these, with at least these to start. I can also help with what might be needed elsewhere. 

1. open science for grad students and advisors
 - adding information about the data generating process/experiment sharing. 
 - This is about both material sharing AND implementation, which I didn't really explain well at the meeting 
2. data sharing in linguistics
 - API google script?
 - Email people for data
 - Shiny app
3. claros website
 - Translate some content to German

**Comment by GabrielaConstantin-Dureci** [comment]
I'd like to contribute to all of them (but the first two are the ones that I am most interested in). 

1. Open science for grad students and advisors

- paragraph/section on positionality and the benefits of it
- institutional role of academia in making these practices more feasible for grad students and early career scholars 

2. Website

- help with tutorials (I have one in mind regarding positionality)
- this semester, I've been doing a certificate on web accessibility, so I would like to share what I've learned. That way, we can make the website accessible to people with disabilities as well (It's really just about being mindful of our formatting at the end of the day, so I would love to help with that!) 
- translation into Romanian

3. Data Sharing in Linguistics

- not sure yet about what I'd like to do in this project, but I'd like to somehow contribute
- I remember we talked about having different people request data (e.g., grad student/ associate prof, female-identifying researcher/male-identifying researcher, etc.). If that's still on the table, I'd like to get involved in the "set-up"

**Comment by GaboSJW** [comment]
I am interested in contributing mainly to data sharing in linguistics. I’m also willing to help with the other two projects whenever needed.


 
 1. open science for grad students and advisors

-  adding information as needed

2. data sharing in linguistics

-  Search for the most cited papers
-  Email people for data
-  Material and Methods part 

3. claros website

- Translate some content into Chinese
- Visual design

**Comment by IvanAndreuRascon** [comment]
I am also interested in all 3 projects 

1. open science for grad students and advisors
Anything that the group might need help with. 

Translation into academic Spanish if needed. 

2. data sharing in linguistics
Email, search for papers, methods, IRB if needed, - also whatever is needed no limitations 

3. claros website

I would like to help with the design and/ or contribute ideas. I think we could also make videos with the material/equipment we have at the lab. 

I can translate it also into Spanish and help with whatever is needed.
