### ISSUE TITLE
Data availability / Isabelle - Ivan 

### ISSUE THREAD

**Issue by IvanAndreuRascon** [RAP-group/meetings#4]
1.	Why this is important: transparency, openness and reproducibility are vital features of science. – more checks on the quality.
2.	A view from the past to the present: Publication requirements (actual or perceived)
3.	What is changing?
a Fears? Critiques, sharing mistakes?
b More honest reproducible works
c  What can you do to change? (how?)
4.	The future
a- Ability to easily reproduce papers.
5.	Wrap up

**Comment by jvcasillas** [comment]
Perfect. CLosing issue and moving to fosil org.
