### ISSUE TITLE
Positionality Statement

### ISSUE THREAD

**Issue by GabrielaConstantin-Dureci** [RAP-group/meetings#5]
**1. What is a positionality statement?**

- Definition

**2. Why is positionality important in research and, specifically, in linguistic research?**

- Positionality addresses where the researcher is coming from when conducting a particular research;

- Recognizing one’s positionality and writing a positionality statement has traditionally been associated with qualitative research and has been more prevalent in subfields of linguistics (e.g., sociolinguistics) or intersecting fields (e.g., anthropology);

- Quantitative research has traditionally been viewed as “hard science” and the quantitative researcher as objective, thus there did not seem to be a need for quantitative researchers to reflect on their positionality;

**3. Why should positionality statements be included in quantitative research as well?**

- Good for validity (see Jafar, 2018)

- The medical field and the psychological field is (slowly) seeing efforts around inclusing positionality in quantitative research (see Jamieson et al., 2022)

- It also addresses diversity and inclusivity gaps in research – connection with DEIB initiatives & connection with making research open and transparent (aka we should know who is doing the research)

**4. Steps for the future**

- Consider your own positionality before starting a project;

- Consider writing a positionality statement for your research; it can be included in additional materials if the word limit is a concern for publication;

- Help create a more open and transparent field for research in linguistics by reflecting on who it is that does the research.

**5. Conclusion** 

NOTES:
I focused on quantitative vs qualitative because (1) positionality is associated with qualitative projects, and (2) when discussing open practices in research, the conversation can be overtaken by the focus on quantitative materials. However, some qualitative practices would benefit openness and transparency in research.

References:
Anisa Jafar (2018): What is positionality and should it be expressed in quantitative studies?
Michelle K. Jamieson; Gisela H. Govaart' & Madeleine Pownall (2022): Reflexivity in Quantitative Research: A Rationale and Beginner’s Guide

**Comment by jvcasillas** [comment]
Perfect, @GabrielaConstantin-Dureci. CLosing this issue and moving it to the fosil org.
