### ISSUE TITLE
General todo

### ISSUE THREAD

**Issue by jvcasillas** [RAP-group/meetings#6]
Leave a comment on this issue regarding the following: 

- project preference
- website info
  - email
  - website personal
  - photo
  - suggestions

**Comment by GabrielaConstantin-Dureci** [comment]
**Project preference**: FOSIL (translations + guide)

**Website info**: Could you add my website as well? https://constantindureci.wixsite.com/profile

**Comment by GaboSJW** [comment]
Project preference 
1.   Guide to open science
2.   FOSIL (Chinese translation) 
3.   Phonetic drift in domestic immersion (learning about forced alignment)

**Comment by thatcher189** [comment]
**Project preference:** Guide to open science, and slowly start working on phonetic drift in domestic immersion
**Website info:**

- jet189@scarletmail.rutgers.edu
- [photo](https://drive.google.com/file/d/11XowPsUqTE3AoGDLsFD49YjX4IoqKXuh/view?usp=sharing)
- Update website + maybe add versions of the site in other languages?

**Comment by IvanAndreuRascon** [comment]
I like all the projects.
I sayto complete the guide to open science by December and then start the other project in the spring. I am in my fellowship year, so I have more time.

**Comment by stephanierod** [comment]
Project preference:
1. Guide to open science
2. FOSIL
3. Phonetic drift in domestic immersion

Website info:
- email: stephanie.rodrig@rutgers.edu
- <img width="155" alt="Screen Shot 2023-09-28 at 4 16 24 PM" src="https://github.com/RAP-group/meetings/assets/123399441/ee773493-9a4d-4465-b700-b57cbad94aba">

**Comment by AMMinetti** [comment]
Project Preference: Guide to open science, phonetic drift in domestic immersion

Website Info:
Email: amm850@scarletmail.rutgers.edu


![RAP Headshot](https://github.com/RAP-group/meetings/assets/145150050/7f009a1c-6e18-4dc4-a90e-55c28e9c8c22)

**Comment by Rhodeg** [comment]
- project preference:  Guide to open science, phonetic drift in domestic immersion
- website info: 
       email: rgg62@scarletmail.rutgers.edu
- photo: 
![0E320F49-4CA3-44CF-825A-0E9328C03A74_1_105_c](https://github.com/RAP-group/meetings/assets/145149873/aacfeeff-2a79-4666-8f7e-a1c6deaec893)

**Comment by Ag1907** [comment]
project preference: guide to open science. FOSIL Translation (Telugu and Hindi) 

email: ag1907@scarletmail.rutgers.edu
photo: 
![juliaprom-17](https://github.com/RAP-group/meetings/assets/120209056/98217898-8901-40c9-8570-ff0242d7f3e9)

**Comment by krishisunlau** [comment]
project preference: open science, phonetic drift in domestic immersion
email: krl105@scarletmail.rutgers.edu
picture: 
<img width="190" alt="image" src="https://github.com/RAP-group/meetings/assets/145789812/8abc444f-583c-4b15-ad55-e8355ee994f9">
