### ISSUE TITLE
preprints

### ISSUE THREAD

**Issue by GaboSJW** [RAP-group/meetings#8]

**Comment by IvanAndreuRascon** [comment]
Ideas to add: 
- Immediate Feedback: Receiving feedback from the community before formal publication can help refine arguments and interpretations.
- Access to Underrepresented Topics: Mainstream journals may prioritize certain dominant themes or languages. Preprints give researchers the opportunity to present work for all topcis
- Promotes Multimodal Data Sharing: audio, visual, data. 
- Support for Early Career Linguists: graduate students/ researchers can introduce their methodologies, datasets, and theoretical contributions to the community without waiting for the extended peer-review process.
-  Academia and Community – broader audience: Preprints are free.
- Flexibility in Content: Preliminary fieldwork reports, replication studies, negative results, or methodological notes which might not find a acle in traditional journals.
- Broading Academic Field: Not every linguist has the possibility of being affiliated with a major institution.
- Fostering a Culture of Open Review: 
- Support for Non-Traditional Formats: extended abstracts, opinion pieces, or annotated datasets.
- Legal Concerns: Authors own the copyright to their work until they transfer it- via a publication agreement.
